---
abstract: 'Extended version of AnyEvent::Handle with additional write options'
author:
  - 'Mons Anderson, C<< <mons at cpan.org> >>'
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Handle-Writer
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  AnyEvent::Handle::Writer:
    file: lib/AnyEvent/Handle/Writer.pm
    version: 0.02
requires:
  AnyEvent: 5
  common::sense: 2
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
